From  gezp/ubuntu-base:20.04-cu110

LABEL maintainer "zhengpeng ge"
MAINTAINER zhengpeng ge "https://github.com/gezp"
ENV REFRESHED_AT 2020-9-27

RUN pip3 install torch torchvision && \
    rm -rf ~/.cache/pip
